name: Create production promotion pull request
on:
  push:
    branches:
      - master
jobs:
  productionPromotion:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: master
      - uses: actions/checkout@v2
        with:
          repository: LWHK/LWHK-Simplified-Chinese-Translation
          path: upstream
          ref: master
      - name: Reset promotion branch
        run: |
          git remote add lwhk https://github.com/LWHK/LWHK-Simplified-Chinese-Translation.git
          git remote -v
          git fetch lwhk master
      - name: check out master
        run: |
          git checkout master
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          branch: fetch_head

