name: Create production promotion pull request
on:
  push:
    branches:
      - master
jobs:
  productionPromotion:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: master
      - uses: actions/checkout@v2
        with:
          repository: LWHK/LWHK-Simplified-Chinese-Translation
          path: upstream
          ref: master
      - name: Reset promotion branch
        run: |
          git config --global credential.helper manager
          git config --global user.email "1716976420@qq.com"
          git config --global user.name "TUsama"
          @"
          protocol=https
          host=github.com
          username=TUsama
          password=${{secrets.PULL_UPSTREAM}}
          "@ > .\1.txt
          gc 1.txt|git credential-manager  store
          ri .\1.txt -Force
          git remote add lwhk https://github.com/LWHK/LWHK-Simplified-Chinese-Translation.git
          git remote -v

      - name: check out master
        run: |
          git branch
          git checkout master
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          branch: lwhk

